# Plugin
gems: [jekyll-paginate, jekyll-lunr-js-search]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

#Ignore export
exclude: ["Gemfile", "Gemfile.lock", "Guardfile", "Rakefile", ".gitignore"]

# Setup
title:               Gilbert Wat
tagline:             his learning in software development and product building
description:         "learn more about Gilbert Wat"
url:                 http://www.getthingsdone.hk
baseurl:             ""
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              Wat Chun Pang Gilbert
  url:               http://www.getthingsdone.hk
  email:             g@getthingsdone.hk 

#Github
github:
  repo:             https://github.com/gilbertwat/gilbertwat.github.io   

#Lunr
lunr_search:
  excludes: [rss.xml, atom.xml, sitemap.txt, 404.html]

# Custom vars
version:             4.0.0
