# Plugin
gems: [
  jekyll-paginate
]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

#Ignore export
exclude: ["Gemfile", "Gemfile.lock", "Guardfile", "Rakefile", ".gitignore", "npm-debug.log"]

# Setup
title:               "Get Things Done"
tagline:             "Weekly article on software development, artificial intelligence and occasionally business"
url:                 http://www.getthingsdone.hk
paginate:            5
paginate_path: "page:num"
host: 0.0.0.0

# About/contact
author:
  name:              Wat Chun Pang Gilbert
  url:               http://www.getthingsdone.hk
  email:             g@getthingsdone.hk 

#Github
github:
  repo:             https://github.com/gilbertwat/gilbertwat.github.io   

# Custom vars
version:             5.0.0

# Defaults
defaults:
 - 
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    comments: true

# Related posts
# For some unknown reason the lsi is not available in guard mode...
# lsi : true

