# Plugin
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-avatar

# Setup
title:               "Get Things Done"
tagline:             "Monthly article on software development, artificial intelligence and occasionally business"
url:                 http://www.getthingsdone.hk
paginate:            10
paginate_path: "page:num"
host: 0.0.0.0

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']

# About/contact
author:
  name:              Gilbert Wat (屈振鵬)
  url:               http://www.getthingsdone.hk
  email:             g@getthingsdone.hk 

#Github
github:
  repo:             https://github.com/gilbertwat/gilbertwat.github.io   

# Custom vars
version:             8.0.0
